// packages/vue/src/MarkerLayer.vue
<script lang="ts" setup>
import * as core from "@canvaskit-tilemap/core";
import { MarkerItem } from "@canvaskit-tilemap/core";
import { toCanvas } from "html-to-image";
import {
  defineProps,
  defineOptions,
  inject,
  onUnmounted,
  ref,
  Ref,
  watchEffect,
} from "vue";

export interface MarkerLayerProps {
  items: MarkerItem[];
  scale?: number;
}

defineOptions({ inheritAttrs: false });

const props = defineProps<MarkerLayerProps>();
const tilemap = inject("tilemap") as Ref<core.Tilemap>;
const element = ref<HTMLDivElement>();
const layer = ref<core.MarkerLayer>();

watchEffect(() => {
  if (tilemap?.value && !layer.value && element.value) {
    toCanvas(element.value).then((image) => {
      layer.value = new core.MarkerLayer({
        ...props,
        image,
        items: props.items.slice(),
      });
      tilemap.value.addLayer(layer.value);
    });
  }
});

onUnmounted(() => {
  if (layer.value) {
    tilemap.value.removeLayer(layer.value);
  }
});
</script>

<template>
  <div style="position: absolute; zindex: -1; left: -100%">
    <div ref="element" :class="$attrs.class">
      <slot></slot>
    </div>
  </div>
</template>

// packages/react/src/marker-layer.tsx
import * as core from "@canvaskit-tilemap/core";
import { ReactElement, ReactNode, useContext, useEffect, useRef } from "react";
import { TilemapContext } from "./tilemap";
import { toCanvas } from "html-to-image";

export interface MarkerLayerProps
  extends Omit<core.MarkerLayerOptions, "image"> {
  children?: ReactNode;
  className?: string;
}

export function MarkerLayer({
  children,
  className,
  ...props
}: MarkerLayerProps) {
  const tilemap = useContext(TilemapContext)!;
  const element = useRef<HTMLDivElement>(null);
  useEffect(() => {
    let layer: core.Layer | null = null;
    toCanvas(element.current!).then((image) => {
      layer = new core.MarkerLayer({ image, ...props });
      tilemap.addLayer(layer);
    });
    return () => {
      if (layer) {
        tilemap.removeLayer(layer);
      }
    };
  }, []);
  return (
    <div style={{ position: "absolute", zIndex: -1, left: "-100%" }}>
      <div ref={element} className={className}>
        {children}
      </div>
    </div>
  );
}
