// packages/vue/src/tile-layer.tsx
import * as core from "@canvaskit-tilemap/core";
import {
  defineComponent,
  inject,
  onUnmounted,
  ref,
  Ref,
  watchEffect,
} from "vue";

interface TileLayerProps extends core.TileLayerOptions {}

export const TileLayer = defineComponent(
  (props: TileLayerProps) => {
    const tilemap = inject("tilemap") as Ref<core.Tilemap>;
    const layer = ref<core.Layer>();
    watchEffect(() => {
      if (tilemap?.value && !layer.value) {
        layer.value = new core.TileLayer(props);
        tilemap.value.addLayer(layer.value);
      }
    });
    onUnmounted(() => {
      if (layer.value) {
        tilemap.value.removeLayer(layer.value);
      }
    });
    return () => null;
  },
);

// packages/react/src/tile-layer.tsx
import * as core from "@canvaskit-tilemap/core";
import { useContext, useEffect } from "react";
import { TilemapContext } from "./tilemap";

export interface TileLayerProps extends core.TileLayerOptions {}

export function TileLayer(props: TileLayerProps) {
  const tilemap = useContext(TilemapContext)!;
  useEffect(() => {
    const layer = new core.TileLayer(props);
    tilemap.addLayer(layer);
    return () => {
      tilemap.removeLayer(layer);
    };
  }, []);
  return <></>;
}
