// packages/react/src/tile-layer.tsx
import * as core from "@canvaskit-tilemap/core";
import { useContext, useEffect } from "react";
import { TilemapContext } from "./tilemap";

export interface TileLayerProps extends core.TileLayerOptions {}

export function TileLayer(props: TileLayerProps) {
  const tilemap = useContext(TilemapContext)!;
  useEffect(() => {
    const layer = new core.TileLayer(props);
    tilemap.addLayer(layer);
    return () => {
      tilemap.removeLayer(layer);
    };
  }, []);
  return <></>;
}

// packages/vue/src/TileLayer.vue
<script lang="ts" setup>
import * as core from "@canvaskit-tilemap/core";
import { defineProps, inject, onUnmounted, ref, Ref, watchEffect } from "vue";

export interface TileLayerProps {
  tileSize?: number;
  minZoom: number;
  maxZoom: number;
  offset?: [number, number];
  getTileUrl: (x: number, y: number, z: number) => string;
}

const props = defineProps<TileLayerProps>();
const tilemap = inject("tilemap") as Ref<core.Tilemap>;
const layer = ref<core.Layer>();

watchEffect(() => {
  if (tilemap?.value && !layer.value) {
    layer.value = new core.TileLayer(props);
    tilemap.value.addLayer(layer.value);
  }
});

onUnmounted(() => {
  if (layer.value) {
    tilemap.value.removeLayer(layer.value);
  }
});
</script>

<template></template>
