// packages/react/src/tilemap.tsx
import * as core from "@canvaskit-tilemap/core";
import { createContext, ReactNode, useEffect, useRef, useState } from "react";

export interface TilemapProps extends Omit<core.TilemapOptions, "element"> {
  children: ReactNode;
  className?: string;
}

export const TilemapContext = createContext<core.Tilemap | undefined>(
  undefined
);

export function Tilemap({ className, ...props }: TilemapProps) {
  const element = useRef<HTMLDivElement>(null);
  const [tilemap, setTilemap] = useState<core.Tilemap>();
  useEffect(() => {
    setTilemap(
      new core.Tilemap({
        element: element.current!,
        ...props,
      })
    );
  }, []);
  return (
    <div ref={element} className={className}>
      {tilemap && (
        <TilemapContext.Provider value={tilemap}>
          {props.children}
        </TilemapContext.Provider>
      )}
    </div>
  );
}

// packages/vue/src/tilemap.tsx
import * as core from "@canvaskit-tilemap/core";
import { defineComponent, provide, ref, watchEffect } from "vue";

interface TilemapProps extends Omit<core.TilemapOptions, "element"> {}

export const Tilemap = defineComponent((props: TilemapProps, { slots }) => {
  const element = ref<HTMLDivElement>();
  const tilemap = ref<core.Tilemap>();
  watchEffect(() => {
    if (element.value && !tilemap.value) {
      tilemap.value = new core.Tilemap({ ...props, element: element.value });
    }
  });
  provide("tilemap", tilemap);
  return () => <div ref={element}>{slots.default?.()}</div>;
});
